#
# MIT License
#
# (C) Copyright 2026 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
core:
  layers:
    base:
      package: vtds-base
      module: vtds_base
      source_type: git
      metadata:
        url: "http://github.com/Cray-HPE/vtds-base.git"
        version: main
    core:
      package: vtds-core
      module: vtds_core
      source_type: git
      metadata:
        url: "http://github.com/Cray-HPE/vtds-core.git"
        version: main
    provider:
      package: vtds-provider-gcp
      module: vtds_provider_gcp
      source_type: git
      metadata:
        url: "http://github.com/Cray-HPE/vtds-provider-gcp.git"
        version: main
    platform:
      package: vtds-platform-ubuntu
      module: vtds_platform_ubuntu
      source_type: git
      metadata:
        url: "http://github.com/Cray-HPE/vtds-platform-ubuntu.git"
        version: main
    cluster:
      package: vtds-cluster-kvm
      module: vtds_cluster_kvm
      source_type: git
      metadata:
        url: "http://github.com/Cray-HPE/vtds-cluster-kvm.git"
        version: main
    application:
      package: vtds-application-openchami
      module: vtds_application_openchami
      source_type: git
      metadata:
        url: "http://github.com/Cray-HPE/vtds-application-openchami.git"
        version: main
  configurations:
  - type: git
    metadata:
      # This brings in the HPE specific settings needed to build an HPE
      # project on GCP.
      repo: http://github.com/Cray-HPE/vtds-configs.git
      version: main
      path: layers/provider/gcp/provider-gcp-hpe-org.yaml
  - type: git
    metadata:
      # This brings in the FSM / SCS Connectivity Demo configuration
      # for the provider layer.
      repo: http://github.com/Cray-HPE/vtds-configs.git
      version: main
      path: layers/provider/gcp/provider-gcp-openChami.yaml
  - type: git
    metadata:
      # This brings in the FSM / SCS Connectivity Demo configuration
      # for the platform layer.
      repo: http://github.com/Cray-HPE/vtds-configs.git
      version: main
      path: layers/platform/ubuntu/platform-ubuntu-openChami.yaml
  - type: git
    metadata:
      # This brings in the FSM / SCS Connectivity Demo configuration
      # for the cluster layer.
      repo: http://github.com/Cray-HPE/vtds-configs.git
      version: main
      path: layers/cluster/kvm/cluster-kvm-openChami.yaml
  - type: git
    metadata:
      # This brings in the FSM / SCS Connectivity Demo configuration
      # for the application layer.
      repo: http://github.com/Cray-HPE/vtds-configs.git
      version: main
      path: layers/application/ubuntu/application-ubuntu-openChami.yaml
  - type: command-line
    # Bring in any configuration files / sources listed on the command
    # line and merge them on top of what has been listed here. This
    # overlay will override matching settings in the above sources.
    metadata: {}
  - type: core-config
    # If there is anything outside the 'core' section of the Core
    # Configuration apply it last to override anything seen up to this
    # point.
    metadata: {}
provider:
  terragrunt:
    terraform_dummy_version: latest
    terragrunt_dummy_version: latest
  project:
    base_name: ochamitest-%%TEST_CLUSTER_NAME%%
  virtual_blades:
    host-blade:
      # A count of 1 is sufficient to build a system on a single blade
      # with 1 management node (ochami-001) and four compute nodes
      # (compute-001, compute-002, compute-003, compute-004).
      #
      # For more compute nodes, increase the number of blades by one for
      # every four additional compute nodes. For additional management
      # nodes, increase the number of blades by one for every management
      # node (each blade has room for one management node and up to 4
      # compute nodes).
      count: 1
cluster:
  node_classes:
    management_node:
      # A node count of 1 creates a single management node.
      node_count: 1
      virtual_machine:
        cpu_count: 4
        memory_size_mib: 8192
    compute_node:
      # A node count of 0 prevents compute nodes from being
      # created. This is the simplest version of OpenCHAMI and will use
      # the RIE RedFish emulator to simulate the existence of compute
      # nodes. This can be increased to four for every virtual blade in
      # the cluster.
      node_count: 4
      host_blade:
        instance_capacity: 4
application:
  deployment:
    mode: quadlet
  rie_services:
    rf-x0c0s3b0:
      delete: true
    rf-x0c0s4b0:
      delete: true
  openchami:
    version: %%OPENCHAMI_VERSION%%  # The openchami version under test
  testing:
    enabled: true
